# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiSigma <- function(signal, deg = 3L) {
    .Call('mwaved_multiSigma', PACKAGE = 'mwaved', signal, deg)
}

waveletThresh <- function(beta, thr, shrinkType = "hard", j0 = 3L, deg = 3L) {
    .Call('mwaved_waveletThresh', PACKAGE = 'mwaved', beta, thr, shrinkType, j0, deg)
}

multiProj <- function(beta, j0 = 3L, j1 = NA_integer_, deg = 3L) {
    .Call('mwaved_multiProj', PACKAGE = 'mwaved', beta, j0, j1, deg)
}

multiThresh <- function(signal, G, alpha = as.numeric( c()), resolution = "smooth", j0 = 3L, j1 = NA_integer_, eta = NA_real_, deg = 3L) {
    .Call('mwaved_multiThresh', PACKAGE = 'mwaved', signal, G, alpha, resolution, j0, j1, eta, deg)
}

multiEstimate <- function(signal, G, alpha = as.numeric( c()), resolution = "smooth", blur = "direct", sigma = as.numeric( c()), j0 = 3L, j1 = NA_integer_, eta = NA_real_, thresh = as.numeric( c()), shrinkType = "hard", deg = 3L) {
    .Call('mwaved_multiEstimate', PACKAGE = 'mwaved', signal, G, alpha, resolution, blur, sigma, j0, j1, eta, thresh, shrinkType, deg)
}

multiCoef <- function(signal, G, alpha = as.numeric( c()), j0 = 3L, j1 = NA_integer_, deg = 3L) {
    .Call('mwaved_multiCoef', PACKAGE = 'mwaved', signal, G, alpha, j0, j1, deg)
}

multiWaveD <- function(signal, G, alpha = as.numeric( c()), resolution = "smooth", blur = "direct", j0 = 3L, j1 = NA_integer_, eta = NA_real_, thresh = as.numeric( c()), shrinkType = "hard", deg = 3L) {
    .Call('mwaved_multiWaveD', PACKAGE = 'mwaved', signal, G, alpha, resolution, blur, j0, j1, eta, thresh, shrinkType, deg)
}

directDetect <- function(x) {
    .Call('mwaved_directDetect', PACKAGE = 'mwaved', x)
}

boxcarDetect <- function(x) {
    .Call('mwaved_boxcarDetect', PACKAGE = 'mwaved', x)
}

directBlur <- function(n, m) {
    .Call('mwaved_directBlur', PACKAGE = 'mwaved', n, m)
}

theoreticalEta <- function(alpha, blur, g_fft, sigma) {
    .Call('mwaved_theoreticalEta', PACKAGE = 'mwaved', alpha, blur, g_fft, sigma)
}

